language: java

sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

jobs:
  include:
    - stage: Build
      script:  mvn -X clean clean deploy -B -s settings.xml

    - stage: Release
      if: branch = master
      script:  mvn clean clean deploy -B -s settings.xml -Prelease
