language: java

sudo: false

before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get update

addons:
  apt:
    packages:
      - openjdk-8-jdk

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

script:
  mvn -s $A5129_IDD_SETTINGS clean install -B
