language: java

sudo: false

before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get update

addons:
  apt:
    packages:
      - openjdk-8-jdk

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

branches:

jobs:
  include:
    - stage: Build
      script:  mvn clean install -B -s settings.xml

    - stage: Release
      if: branch = master
      script:  mvn -B -s settings.xml -Dtag=guard-1.2 release:prepare -DreleaseVersion=1.2 -DdevelopmentVersion=2.0-SNAPSHOT
