language: java

sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

jobs:
  include:
    - stage: Build
      if: branch != master
      script:  mvn clean deploy --settings ~/settings.xml -Prelease

    - stage: Prepare release
      if: branch = master
      script:  mvn -Prelease release:prepare --settings ~/settings.xml

    - stage: Release
      if: branch = master
      script:  mvn -Prelease release:perform --settings ~/settings.xml
