language: java

sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

jobs:
  include:
    - stage: Build
      if: branch != master
      script:  mvn clean package

    - stage: Prepare release
      if: branch = master AND env(DEV_VERSION) AND env(RELEASE_VERSION)
      script:  mvn -Prelease -DdryRun=true -Dtag=Guard-${env.RELEASE_VERSION} release:prepare -DreleaseVersion=${env.RELEASE_VERSION} -DdevelopmentVersion=${env.DEV_VERSION}-SNAPSHOT --batch-mode --settings settings.xml

    - stage: Perform Release
      if: branch = master AND env(DEV_VERSION) AND env(RELEASE_VERSION)
      script:  mvn -Prelease release:perform --settings settings.xml
