language: java

sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

jobs:
  include:
    - stage: Build
      if: branch != master
      script:  mvn clean package

    - stage: Prepare release
      if: branch = master AND env(RELEASE) = true
      script:  mvn -B -Prelease -DdryRun=true release:prepare --settings settings.xml

    - stage: Perform Release
      if: branch = master AND env(RELEASE) = true
      script:  mvn -B -Prelease release:perform --settings settings.xml
