language: java

sudo: false

before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get update

addons:
  apt:
    packages:
      - openjdk-8-jdk

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

jobs:
  include:
    - stage: Build
      script:  mvn clean clean deploy -B -s settings.xml

    - stage: Release
      if: branch = master
      script:  mvn clean clean deploy -B -s settings.xml
