language: java

sudo: false

before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa
  - sudo apt-get update

addons:
  apt:
    packages:
      - openjdk-8-jdk

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

script:
  mvn clean package -B
