language: java

sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

jobs:
  include:
    - stage: Build
      if: branch != master
      script:  mvn -B clean package

    - stage: Release
      if: branch = master AND env(RELEASE_VERSION) IS present AND env(DEV_VERSION) IS present AND type != push AND type != pull_request
      script:  git checkout "$TRAVIS_BRANCH" && mvn -B -Prelease release:clean release:prepare release:perform --settings settings.xml
